### ISSUE TITLE
为什么总是出现 .mltk 的一些导入错误？有什么解决方法吗？

### ISSUE THREAD

**Issue by bilibili8494** [NetManAIOps/GTrace#1]
![image](https://github.com/NetManAIOps/GTrace/assets/108794412/fc694022-04eb-45cb-8795-aa24f2b9d511)

**Comment by xiez22** [comment]
请确认是否已经安装了requirements.txt里面“./deployment/anomaly_detection/ml-essentials”这一项，如果安装好了，可以尝试import mltk检查是否安装成功。如果仍然不行的话，可以提供一个更详细的报错日志和运行环境

**Comment by bilibili8494** [comment]
感谢你的回复，这个问题已经解决了，不过我现在有了新的问题，希望您能帮帮我，1.在我训练完成以后，会生成一个result的文件夹，但是里面只有两个config文件，并没有其他结果。但是我在调试过程中可以看到auc和f 值，为什么没有保存到result文件夹中？
2. dataset-b 中的数据集是.db 格式的，我在pycharm中下载插件sqlite可以打开，打开以后里面不是中文，也不是英文，是一些看起来像16进制的文件，请问这是处理过的数据集吗？还是我的打开姿势有误，应当用什么？



---原始邮件---
发件人: "Xie ***@***.***&gt;
发送时间: 2023年12月23日(周六) 下午4:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NetManAIOps/GTrace] 为什么总是出现 .mltk 的一些导入错误？有什么解决方法吗？ (Issue #1)




 
请确认是否已经安装了requirements.txt里面“./deployment/anomaly_detection/ml-essentials”这一项，如果安装好了，可以尝试import mltk检查是否安装成功。如果仍然不行的话，可以提供一个更详细的报错日志和运行环境

**Comment by xiez22** [comment]
1. 是的，由于代码框架用了我们实验室自己写的[ml-essential](https://github.com/haowen-xu/ml-essentials)，会自动生成文result文件夹。但是为了简化实验配置，我们在这个代码里把保存实验结果的代码删掉了（原来的代码会把结果保存在ml-essential关联的mongo数据库中，配置较为麻烦）。所以目前results文件夹应该没有保存结果，只能看输出。

2. dataset-b的原始文件（无标注）可以在dataset_b/raw文件夹下找到。sqlite里面存的是已经经过了预处理（含测试集标注）与压缩的TraceGraph二进制数据（经过了pickle编码和snappy压缩），所以看上去是乱码的。如果需要将训练与测试数据转换成原来的格式，需要基于当前的[TraceGraph读取代码](https://github.com/NetManAIOps/GTrace/blob/d2886514e3fa5ed2d79b3ed232d7b650d293c60f/tracegnn/data/trace_graph.py#L398)，根据读取的TraceGraph自行编写导出部分的代码。

**Comment by bilibili8494** [comment]
十分感谢您的再次回复！接下来我会试着将数据转换成原来的格式，便于自己理解。再仔细学习模型的训练细节，若遇到困惑希望能再和您讨论。(˵¯͒〰¯͒˵)

---原始邮件---
发件人: "Xie ***@***.***&gt;
发送时间: 2023年12月23日(周六) 下午4:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NetManAIOps/GTrace] 为什么总是出现 .mltk 的一些导入错误？有什么解决方法吗？ (Issue #1)




  
 
是的，由于代码框架用了我们实验室自己写的ml-essential，会自动生成文result文件夹。但是为了简化实验配置，我们在这个代码里把保存实验结果的代码删掉了（原来的代码会把结果保存在ml-essential关联的mongo数据库中，配置较为麻烦）。所以目前results文件夹应该没有保存结果，只能看输出。
 
 
 
dataset-b的原始文件（无标注）可以在dataset_b/raw文件夹下找到。sqlite里面存的是已经经过了预处理（含测试集标注）的二进制数据（经过了pickle和snappy编码），所以看上去是乱码的。如果需要将训练与测试数据转换成原来的格式，需要基于当前的数据库读取代码，自行编写导出部分的代码。
