### ISSUE TITLE
请问 visualization 中case_0.pkl 和 case_1.pkl 分别是什么格式的数据来源，我尝试了pickle 和 joblib等方法都无法解析？

### ISSUE THREAD

**Issue by bilibili8494** [NetManAIOps/GTrace#2]

**Comment by xiez22** [comment]
You need to use snappy.decompress before pickle.load. Refer to the code below to see its usage:
https://github.com/NetManAIOps/GTrace/blob/b0c11badfb518fdf94206132b38dc69092f26507/tracegnn/visualization/visualization_tool.py#L21
