### ISSUE TITLE
请问raw是怎么划分到训练集验证集测试集，数据条数对不上，是有删掉raw中的一些数据吗？

### ISSUE THREAD

**Issue by bilibili8494** [NetManAIOps/GTrace#5]

**Comment by xiez22** [comment]
数据集是经过标注和采样的，我们公开的raw数据应该是原始的未经标注的数据。数据标注之后，我们通过随机采样的方法采样出训练（不含标注）、验证（不含标注）和测试集（含标注）。raw数据是供您自行探索的，可以自行对raw数据进行标注与划分。或者直接使用我们提供的训练、验证和测试数据
